{% set name = "django-nested-inline" %}
{% set version = "0.3.7" %}
{% set md5 = "84e153f123e7801963e22424916bcc8b" %}
{% set build = 0 %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    md5: {{ md5 }}
    patches:
        - zipsafe.patch

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - example
        - nested_inline

about:
    home: https://github.com/s-block/django-nested-inline
    license: MIT License
    summary: Recursive nesting of inline forms for Django Admin

extra:
    recipe-maintainers:
        - kwilcox
