{% set name = "django-nested-inline" %}
{% set version = "0.4.4" %}
{% set md5 = "5df17149db462f00efb7d9cbb81c0da7" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}
  patches:
    - zipsafe.patch

build:
  number: {{ build }}
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - example
    - nested_inline

about:
  home: https://github.com/s-block/django-nested-inline
  license: MIT
  license_file: LICENSE
  summary: Recursive nesting of inline forms for Django Admin

extra:
  recipe-maintainers:
    - kwilcox
