# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "fqaC8zMhJ65QHyOp1efY8xLQZN6k7pWPUSzngJ3fqpwMLMebkclgyp5I4xZTRSG9UyWDU/7ht/j4jJPnRnz534LNiMci0qtQ7H9qBUoxcAXCGPx2xUb66jWYvaCqFGYoihM12frPVeL/IIs79Eom1mK/1ywyUxDOvb/XRp0f4MuHDfh0w8pxEQspCYj8bvPVymfXRGOw+TInWXI1MRTZVRDdJi5lKjIpgvMUUNEhRB+gPanHXL+JrsYGfhy/V4lYICmOqPbDwdEBNAsvnjntov+DN2ukMnYPnYSdNVlc17SD2KsrpTDEy3KNYrX5yBrV5T4/JjBLgzvVcsBINv96hK+wSESE0kOIG+LHLL8RUNLgc7qydF5rwOBlJcSNnXsSukdEr19StGls3uJWzD7yTvB7d4T8Rfz5BfYEpABvyZ7YE7HVHDAzaKY8S7jXHza9KoHJLKIYhfpzPP5He2u6kGvmNErneEzE8i9WMCKSviXy94sQ5GxQCx4IWPi293bjiWBXJJ9U7Pl2Jco3cn49y8tN2+uBYErWpHXJXwh9ltr66QRQUnuQfj5HZaoxLNk/0davUz78EFU4w/6tQuXeTBfVPRw/Q2O5E69tnAl4QxNkLKF9BghjoQQUWWnjWhIowPu3qyYeGOOu6m6QQaeYSj9z1e8jTe863ZlMg7f3eXU="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
