appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Onph0O2SinK7OXAF2AluIv98J6mr5XPCGw/OK+0pHCkBwDT7jITViXpg40BLgH8w16VhV1lGZM+hbVeANYjNkgnZDWa6wymv5ntHfTR0/XBPBNYhqFptGpDuNOc3gTC5rxOVHqN77ELTFVHPGqiotfFaA/3WoCUNf6GphmVE5YH6KzBtIuhiFjT951JYvu/KIJTgyvs/aWeZxSVDgDvajHGN9y55MDQZBWK1Ot3IfMRkihC2NaDwOuYMJBP/d5kcZRBtFPZA02kBJmw3+7fBl1N4bYPt0bXyEPCFezEdaUdIs5DmYIJOhYrMrDzlaekeMUAZTcRvispbW3ax6PHBt+mdEZkusTyDurxuX/H87VdInYBBv2JCGxezFGanKbBUWzrsgsPEu5qzgUUo1fYOZUq2uWi4kE9RcheIZWjN1zjgsTFrqbukeXGJGAXDrptXnHRoZeGnkptjJNC3xfuyfc9sCDz2X/am3gED/zGD9YAch51ztygapIcuxJwy0sjE40u9QRtXHvsxURDZ55X581qz38hUilTcyZTcRnqXF1HDu0d6YDZtPGMZBF4ZqFmKIj8iQRhq+GRqXBXBWwbGOxi9tKtToDUp9ixMlx5uR9mCRwVVa2nYiM9xBM/VV+Q67z3MApJ9IoBd7WRiIKa/noi4/mvZiso5y81q3CskaNU=}
provider:
  win: azure
conda_forge_output_validation: true
