travis:
  secure:
    BINSTAR_TOKEN: fqaC8zMhJ65QHyOp1efY8xLQZN6k7pWPUSzngJ3fqpwMLMebkclgyp5I4xZTRSG9UyWDU/7ht/j4jJPnRnz534LNiMci0qtQ7H9qBUoxcAXCGPx2xUb66jWYvaCqFGYoihM12frPVeL/IIs79Eom1mK/1ywyUxDOvb/XRp0f4MuHDfh0w8pxEQspCYj8bvPVymfXRGOw+TInWXI1MRTZVRDdJi5lKjIpgvMUUNEhRB+gPanHXL+JrsYGfhy/V4lYICmOqPbDwdEBNAsvnjntov+DN2ukMnYPnYSdNVlc17SD2KsrpTDEy3KNYrX5yBrV5T4/JjBLgzvVcsBINv96hK+wSESE0kOIG+LHLL8RUNLgc7qydF5rwOBlJcSNnXsSukdEr19StGls3uJWzD7yTvB7d4T8Rfz5BfYEpABvyZ7YE7HVHDAzaKY8S7jXHza9KoHJLKIYhfpzPP5He2u6kGvmNErneEzE8i9WMCKSviXy94sQ5GxQCx4IWPi293bjiWBXJJ9U7Pl2Jco3cn49y8tN2+uBYErWpHXJXwh9ltr66QRQUnuQfj5HZaoxLNk/0davUz78EFU4w/6tQuXeTBfVPRw/Q2O5E69tnAl4QxNkLKF9BghjoQQUWWnjWhIowPu3qyYeGOOu6m6QQaeYSj9z1e8jTe863ZlMg7f3eXU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
